export type Theme = "dark" | "light";

export type ChapterId = "opening" | "hero" | "journey" | "present" | "archive";

export const profile = {
  name: "Sameer Majeed",
  firstName: "Sameer",
  lastName: "Majeed",
  designations: ["ACA", "FIPA", "FFA"] as const,
  headline: "FP&A Manager",
  roles: ["FP&A Manager", "Chartered Accountant", "Financial Strategy & Analysis"],
  location: "Riyadh, Saudi Arabia",
  email: "sameerpk_majeed@hotmail.com",
  linkedin: "https://www.linkedin.com/in/sameer-majeed-aca-fipa-ffa-85a38969/",
  portrait: "/portrait/sameer-majeed.png",
  experienceLabel: "10+ years",
  experienceFields: ["Finance", "Audit", "FP&A"],
  about:
    "I am passionate qualified chartered accountant with more than ten years of diversified experiences in Finance, Accounts and Audit with strong record of leadership and delivery of services in multicultural working environment, combining broad exposure in relevant fields.",
} as const;

export const chapters = [
  { id: "opening", index: "01", label: "Opening", theme: "dark" as Theme, year: "2014 — Present", category: "Journey", place: "—" },
  { id: "hero", index: "02", label: "Sameer", theme: "dark" as Theme, year: "Present", category: "Identity", place: "Riyadh" },
  { id: "journey", index: "03", label: "Journey", theme: "dark" as Theme, year: "2014 — 2025", category: "Career", place: "Lahore → Riyadh" },
  { id: "present", index: "04", label: "Present", theme: "dark" as Theme, year: "2025 — Present", category: "Fintech", place: "Riyadh" },
  { id: "archive", index: "05", label: "Credentials", theme: "dark" as Theme, year: "2021 — 2024", category: "Archive", place: "Verified" },
] as const;

export const navLinks = [
  { href: "#opening", label: "Journey" },
  { href: "#journey", label: "Experience" },
  { href: "#archive", label: "Credentials" },
  { href: "#contact", label: "Contact" },
] as const;

export const roles = [
  {
    id: "flooss",
    year: "2025",
    yearEnd: "Present",
    start: "March 2025",
    end: "Present",
    duration: "1 yr 7 mos",
    company: "Flooss",
    companyFull: "Flooss",
    title: "Financial Planning and Analysis Manager",
    location: "Riyadh, Saudi Arabia",
    workMode: "On-site",
    current: true,
    url: "https://flooss.sa/en/",
    highlights: [
      "Prepare and present monthly, quarterly, and year-end financial reports for senior management.",
      "Develop dashboards and KPIs to monitor business performance.",
      "Prepare annual budgets, quarterly forecasts and long-range financial plans.",
      "Track actual performance against budget and forecast, and explain key variances.",
      "Prepare comprehensive financial projections based on reasonable assumptions.",
    ],
    themes: [
      "Monthly, quarterly and year-end reporting",
      "Dashboards & KPIs",
      "Annual budgets",
      "Quarterly forecasts",
      "Long-range plans",
      "Actual vs budget",
      "Variance analysis",
      "Financial projections",
    ],
  },
  {
    id: "alrajhi",
    year: "2023",
    yearEnd: "2025",
    start: "January 2023",
    end: "March 2025",
    duration: "2 yrs 3 mos",
    company: "Al Rajhi Bank",
    companyFull: "Al Rajhi Bank",
    title: "Financial Planning and Analysis Specialist",
    location: "Riyadh, Saudi Arabia",
    workMode: "On-site",
    current: false,
    highlights: [
      "Develop, present, and oversee financial budgets on an annual and quarterly basis.",
      "Collaborate with executives, project managers, and cross-departmental leadership to set budget targets.",
      "Evaluate budget proposals and financial requests for viability.",
      "Forecast financial needs throughout the year.",
      "Track results against key financial targets.",
      "Prepare cost estimates and plans, with the necessary reporting, documentation, and financial assessments.",
      "Identify, flag, and analyze potential financial and budgetary risks.",
      "Provide financial summaries, reports, and recommendations as needed.",
      "Coordinate with the technical team to prepare dashboards in Power BI.",
    ],
    themes: [
      "Annual budgets",
      "Quarterly budgets",
      "Forecasting",
      "Cost estimates",
      "Financial risk identification",
      "Management reporting",
      "Power BI collaboration",
      "Cross-functional planning",
    ],
  },
  {
    id: "najm",
    year: "2021",
    yearEnd: "2023",
    start: "October 2021",
    end: "January 2023",
    duration: "1 yr 4 mos",
    company: "Najm",
    companyFull: "Najm Company for Insurance Services",
    title: "Financial Planning and Management Reporting Specialist",
    location: "Riyadh, Saudi Arabia",
    workMode: null,
    current: false,
    highlights: [
      "Preparation of monthly, quarterly and annual management financial statements as per IFRSs.",
      "Enhancing the quality of monthly management reporting.",
      "Implementing procedures to ensure effective and efficient operations of the Finance Department.",
      "Generate analyses and financial reports as required by higher management.",
      "Analysis of actual reports against budgeted and forecasted reports.",
      "Coordinating with the budgeting team to prepare budgets on a reasonable basis.",
      "Supporting the SAP Coordinator to improve processes of the Planning, Finance and Control Department.",
      "Monitoring SAP system performance across purchasing, procurement, general accounting, analytical accounting and reports.",
      "Maintain the chart of accounts — including new accounts, cost centers and profit centers — with authorized, documented changes.",
    ],
    themes: [
      "IFRS reporting",
      "Management reporting",
      "Budgeting",
      "Forecasting",
      "SAP",
      "Chart of accounts",
      "Cost centers",
      "Profit centers",
      "Financial analysis",
    ],
  },
  {
    id: "zoom-manager",
    year: "2021",
    yearEnd: "2021",
    start: "January 2021",
    end: "September 2021",
    duration: "9 mos",
    company: "Zoom Marketing Oils",
    companyFull: "Zoom Marketing Oils",
    title: "Manager Accounts & Finance",
    location: "Lahore, Punjab, Pakistan",
    workMode: null,
    current: false,
    parentTenure: "Full-time · 3 yrs 3 mos",
    highlights: [
      "Led accounts and finance through a period of widening operational responsibility.",
    ],
    themes: [
      "Financial control",
      "Management reporting",
      "Banking",
      "Tax",
      "ERP",
    ],
  },
  {
    id: "zoom-deputy",
    year: "2018",
    yearEnd: "2021",
    start: "July 2018",
    end: "January 2021",
    duration: "2 yrs 7 mos",
    company: "Zoom Marketing Oils",
    companyFull: "Zoom Marketing Oils",
    title: "Deputy Manager Finance",
    location: "Lahore District, Punjab, Pakistan",
    workMode: null,
    current: false,
    parentTenure: "Full-time · 3 yrs 3 mos",
    highlights: [
      "Developing and updating accounting, finance, and management procedures and policies.",
      "Ensure the pricing mechanism for petroleum products suggested by OGRA on a monthly basis.",
      "Monthly and periodic reporting to management and the CEO.",
      "Supervision of dealings with banks for financing import LCs, SECP and other government organizations.",
      "Managing cash flows, profit and loss as well as working capital budgets.",
      "Arranging new sources of finance for the company's debt facilities.",
      "Ensure compliance with banking regulations.",
      "Liaison with external auditors for the statutory audit.",
      "Supervision of income tax and sales tax affairs specific to the petroleum industry.",
      "Review and e-file monthly sales tax returns and withholding tax statements.",
      "Supervision of implementation of accounting software (SAP Business One).",
    ],
    themes: [
      "Cash flow",
      "Working capital",
      "Tax",
      "Banking",
      "ERP / SAP Business One",
      "Audit liaison",
      "Management procedures",
      "Regulatory compliance",
    ],
  },
  {
    id: "varioline",
    year: "2017",
    yearEnd: "2018",
    start: "November 2017",
    end: "June 2018",
    duration: "8 mos",
    company: "Varioline Services",
    companyFull: "Varioline Services",
    title: "Head of Accounts",
    location: "Lahore",
    workMode: null,
    current: false,
    highlights: [
      "Providing and interpreting financial information.",
      "Conducting reviews and evaluations for cost reduction opportunities.",
      "Producing accurate financial reports.",
      "Managing budgets.",
      "Managing accurate and timely monthly, quarterly and year-end closing.",
      "Liaison with external auditors for the statutory audit.",
      "Preparing aging analysis of customers and vendors to maintain the cash flow cycle.",
      "Review and e-file monthly sales tax returns and withholding tax statements.",
      "Ensure compliance with corporate and tax laws, and prepare replies to queries from authorities.",
      "Manage the General Ledger, Accounts Receivable, Accounts Payable and Inventory modules of an Oracle-based ERP.",
    ],
    themes: [
      "Financial information",
      "Cost control",
      "Financial reporting",
      "Budget management",
      "General ledger",
      "Receivables / payables",
      "Inventory",
      "Cash flow",
      "ERP Oracle",
      "Audit liaison",
    ],
  },
  {
    id: "hassan-naeem",
    year: "2014",
    yearEnd: "2017",
    start: "June 2014",
    end: "November 2017",
    duration: "3 yrs 6 mos",
    company: "Hassan Naeem & Co",
    companyFull: "Hassan Naeem & Co",
    network: "UHY",
    title: "Audit Associate",
    location: "Lahore",
    workMode: null,
    current: false,
    highlights: [
      "Planning and execution of audit in accordance with International Standards on Auditing.",
      "Evaluation of internal controls and drafting recommendations to management and those charged with governance.",
      "Managing and delegating work to engagement team members across multiple engagements — from planning to finalization.",
      "Prepare and critically review final deliverables to meet IFRS and local financial reporting requirements.",
      "Supervised and reviewed the work of the engagement team, with timely feedback and training.",
      "Resolution of accounting and technical issues raised by clients.",
      "Keep up-to-date with changes to accounting standards and their impact from planning through finalization.",
    ],
    themes: [
      "International Standards on Auditing",
      "Internal controls",
      "IFRS",
      "Financial reporting",
      "Client engagements",
      "Technical accounting",
      "Regulatory requirements",
    ],
  },
] as const;

export const constellation = [
  {
    year: "2014",
    company: "Hassan Naeem & Co",
    title: "Audit Associate",
    location: "Lahore",
    duration: "Jun 2014 — Nov 2017 · 3 yrs 6 mos",
    core: "Audit in accordance with International Standards on Auditing, IFRS reporting, and internal controls.",
  },
  {
    year: "2017",
    company: "Varioline Services",
    title: "Head of Accounts",
    location: "Lahore",
    duration: "Nov 2017 — Jun 2018 · 8 mos",
    core: "Financial information, closing, budgets, and Oracle ERP ledgers.",
  },
  {
    year: "2018",
    company: "Zoom Marketing Oils",
    title: "Deputy Manager Finance",
    location: "Lahore",
    duration: "Jul 2018 — Jan 2021 · 2 yrs 7 mos",
    core: "Cash flow, tax, banking, SAP Business One, and statutory audit liaison.",
  },
  {
    year: "2021",
    company: "Zoom Marketing Oils → Najm",
    title: "Manager Accounts & Finance, then FP&A reporting in Riyadh",
    location: "Lahore → Riyadh",
    duration: "Jan 2021 — Jan 2023",
    core: "From accounts leadership to IFRS management reporting and SAP.",
  },
  {
    year: "2023",
    company: "Al Rajhi Bank",
    title: "Financial Planning and Analysis Specialist",
    location: "Riyadh",
    duration: "Jan 2023 — Mar 2025 · 2 yrs 3 mos",
    core: "Budgets, forecasts, risk flags, and Power BI dashboards.",
  },
  {
    year: "2025",
    company: "Flooss",
    title: "FP&A Manager",
    location: "Riyadh",
    duration: "Mar 2025 — Present",
    core: "Reporting, KPIs, budgets, forecasts, and financial projections in fintech.",
  },
  {
    year: "Now",
    company: "Flooss",
    title: "Financial Planning and Analysis Manager",
    location: "Riyadh, Saudi Arabia",
    duration: "Present",
    core: "Finance at the speed of fintech — planning what comes next.",
  },
] as const;

export const credentials = [
  {
    id: "coursera",
    name: "Financial Accounting: Advanced Topics",
    issuer: "University of Illinois at Urbana-Champaign",
    short: "",
    via: "Coursera",
    year: "2021",
    date: "10 July 2021",
    verifyUrl: "https://coursera.org/verify/G3V44P73DPXB",
    image: "/certificates/coursera-financial-accounting.png",
    orientation: "landscape" as const,
    details: ["Authorized by University of Illinois at Urbana-Champaign", "Offered through Coursera"],
  },
  {
    id: "fipa",
    name: "Fellow",
    issuer: "Institute of Public Accountants",
    short: "FIPA",
    year: "2022",
    date: "15 March 2022",
    membershipNo: "330909",
    location: "Melbourne, Australia",
    image: "/certificates/fipa-fellow.png",
    orientation: "portrait" as const,
    details: ["Admitted as Fellow of the Institute of Public Accountants", "Member No. 330909"],
  },
  {
    id: "ffa",
    name: "Fellow",
    issuer: "Institute of Financial Accountants",
    short: "FFA",
    year: "2022",
    date: "15 March 2022",
    membershipNo: "IPA330909",
    image: "/certificates/ffa-fellow.png",
    orientation: "portrait" as const,
    details: ["Admitted as a Fellow", "Member No. IPA330909", "A member of the IPA Group"],
  },
  {
    id: "socpa",
    name: "Certificate of Associate Membership",
    issuer: "Saudi Organization for Chartered and Professional Accountants",
    short: "SOCPA",
    year: "2023",
    date: "3 March 2023",
    membershipNo: "133181",
    idNumber: "2509343246",
    validityNote: "Certificate validity stated as 3 March 2023 — 3 March 2024",
    image: "/certificates/socpa-associate.png",
    orientation: "landscape" as const,
    details: [
      "Associate member certificate",
      "Membership No. 133181",
      "Effective 3 March 2023",
    ],
  },
  {
    id: "icap",
    name: "Associate",
    issuer: "The Institute of Chartered Accountants of Pakistan",
    short: "ACA",
    year: "2024",
    date: "20 August 2024",
    issued: "22 August 2024",
    membershipNo: "12797",
    certificateNo: "204543",
    image: "/certificates/icap-associate.png",
    orientation: "portrait" as const,
    details: [
      "Admitted as an Associate of ICAP",
      "Membership Reg. No. 12797",
      "Certificate dated 22 August 2024, Karachi",
    ],
  },
] as const;

export const disciplines = [
  "FP&A",
  "Forecasting",
  "Budgeting",
  "Financial Modelling",
  "Management Reporting",
  "Financial Analysis",
  "Accounting",
  "Audit",
  "IFRS",
  "SAP",
  "ERP",
  "Stakeholder Management",
] as const;

export const capabilities = [
  { name: "FP&A", detail: "Budgets, forecasts, and financial projections." },
  { name: "Forecasting", detail: "Quarterly forecasts and long-range plans." },
  { name: "Budgeting", detail: "Annual and quarterly budget planning." },
  { name: "Reporting", detail: "IFRS and management reporting." },
  { name: "Financial Analysis", detail: "Variance analysis and performance review." },
  { name: "Financial Control", detail: "Audit, ERP, and internal controls." },
] as const;

export const services = [
  "Financial Consulting",
  "Accounting",
  "Financial Accounting",
  "Financial Advisory",
  "Budgeting",
  "Financial Analysis",
  "Financial Planning",
  "Financial Reporting",
] as const;

export const ledgerEntries = [
  { year: "2014", term: "Audit" },
  { year: "2017", term: "Accounts" },
  { year: "2018", term: "Finance" },
  { year: "2021", term: "Planning" },
  { year: "2023", term: "FP&A" },
  { year: "2025", term: "Riyadh" },
  { year: "", term: "Flooss" },
] as const;

export const arc = [
  "Audit",
  "Accounting",
  "Financial Control",
  "Reporting",
  "Planning",
  "FP&A",
  "Fintech",
] as const;

export function getRole<T extends (typeof roles)[number]["id"]>(id: T) {
  return roles.find((role) => role.id === id)! as Extract<(typeof roles)[number], { id: T }>;
}
